feature/1: add commit message validation step test

diff --git a/.github/workflows/check-naming-conventions.yml b/.github/workflows/check-naming-conventions.yml
--- a/.github/workflows/check-naming-conventions.yml
+++ b/.github/workflows/check-naming-conventions.yml
@@ -26,3 +26,27 @@ jobs:
             exit 1
           fi
         shell: bash
+
+      - name: Validate commits messages
+        run: |
+          # Get commits specific to the PR branch
+          commits=$(git log --format=%s origin/${{ github.head_ref }}..HEAD)
+
+          echo "Checking commits"
+
+          pattern="^(feature|hotfix|fix|chore|issue)\/[0-9]+: "
+
+          while read -r commit; do
+            # Check if the commit is a merge commit
+            if [[ "$commit" == "Merge pull request"* ]]; then
+              echo "Skipping merge commit: \"$commit\""
+              continue
+            fi
+
+            # Validate the message pattern
+            if ! [[ $commit =~ $pattern ]]; then
+              echo "Invalid commit: \"$commit\"""
+              echo "Use format: feature/123: Add some feature"
+              exit 1
+            fi
+          done <<< "$commits"
